version: "3.8"
services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: osaka
      MYSQL_PASSWORD: osaka
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./docker_files/init.sql:/init.sql
      - ./docker_files/sql_setup.sh:/docker-entrypoint-initdb.d/init.sh

volumes:
  mariadb_data:

